#!/usr/bin/env python3
# Derive claude-agents/*.md from skills/ — the Claude Code subagent projection,
# sibling to render-agents.py's Codex toml projection.
#
# Why these are SHIMS and not inlined personas. render-agents.py inlines the
# whole persona plus the shared core into each toml, because the Codex CLI has
# no skills mechanism to defer to — the toml has to be self-contained. Claude
# Code does have one, and sync.sh already puts every persona under
# ~/.claude/skills/. Inlining here would put each persona in the profile twice
# and let the copies drift the moment one is edited, which is the exact failure
# render-agents.py's own header records: 174 lines that landed in skills/ and
# never crossed, 63 stale lines left behind, invisible to a plain diff. One
# source of truth, two thin projections.
#
# The shim carries the skill reference two ways on purpose: the frontmatter
# `skills:` field, and a body instruction naming the same skill. If the field
# is honored the body is redundant reinforcement; if it is ever ignored or
# dropped from the schema, the body alone still routes the subagent to the
# right place. A generated file that silently becomes a no-op is worse than a
# slightly redundant one.
#
# What this buys, precisely: skills and subagents have OPPOSITE precedence.
# A personal ~/.claude/skills entry beats a repo's .claude/skills, but a repo's
# .claude/agents beats ~/.claude/agents. So these give the roster as subagents
# in every repo that ships none of its own, and lose to any repo that does.
#
# Build step (skills/ -> claude-agents/), not a deploy step (repo -> profiles);
# sync.sh does the latter. Deliberately not wired together, same as
# render-agents.py: folding this into sync.sh would make it mutate tracked
# files on every run.
#
# Usage: python3 render-claude-agents.py           # regenerate, idempotent
#        python3 render-claude-agents.py --check   # exit 1 on drift, write nothing
import importlib.util, os, sys, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, 'claude-agents')

# Reuse render-agents.py's parsing rather than reimplementing it. The hyphen in
# the filename blocks a plain import, so load it by path — duplicating
# has_persona_line() or frontmatter_desc() here would create a second surface
# that drifts from the first, which is the thing both scripts exist to prevent.
_spec = importlib.util.spec_from_file_location(
    'render_agents', os.path.join(ROOT, 'render-agents.py'))
ra = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ra)


def render(p, root=ROOT):
    """claude-agents/<p>.md — frontmatter plus a two-sentence body.

    The description is copied verbatim from the skill's frontmatter, never
    rewritten or shortened: it is the trigger surface for both mechanisms, and
    Claude under-triggers skills already. A subagent whose description drifts
    from its skill's is a persona you can reach one way and not the other.
    """
    sk = open('%s/skills/%s/SKILL.md' % (root, p)).read()
    desc = ra.frontmatter_desc(sk, name=p)
    return (
        '---\n'
        'name: %s\n' % p
        + 'description: >\n  %s\n' % desc
        + 'skills:\n  - %s\n' % p
        + '---\n\n'
        + 'You are %s. The `%s` skill is preloaded into your context at startup '
          'by the `skills:` field above — its full content, not just its '
          'description. That skill is the complete definition of this persona: '
          'its voice, its bounds, what it must not touch, and how it hands off. '
          'Follow it. Nothing about how %s works lives in this file.\n\n'
          'If the skill is somehow absent from your context, say so plainly '
          'rather than improvising a persona from this stub — a %s running on '
          'guesswork is worse than one that reports it cannot start.\n\n'
          'Generated by render-claude-agents.py from skills/%s/SKILL.md. '
          'Hand-editing is a no-op; the next build overwrites it. Change the '
          'skill instead.\n' % (p, p, p, p, p))


def regenerate_all(root=ROOT, check=False):
    """Rewrite every persona's agent file. Returns (written, orphans).

    Iterates personas() — the skills whose SKILL.md opens with a canonical
    persona declaration — not claude-agents/*.md, so a newly added persona gets
    a file the first time this runs. A utility skill (handoff, review-loop,
    devils-advocate) has no declaration and correctly gets none: the absence of
    the line is the signal, exactly as it is for the toml projection.

    An orphan is a claude-agents/*.md with no matching persona in skills/ — a
    skill renamed, removed, or demoted to a utility. Reported by name and left
    untouched rather than deleted, so a rename is a visible warning instead of
    a silent disappearance.
    """
    names = ra.personas(root)
    rendered = {p: render(p, root) for p in names}

    written = []
    for p, text in sorted(rendered.items()):
        path = os.path.join(OUT, p + '.md')
        if not os.path.exists(path) or open(path).read() != text:
            written.append(p)
            if not check:
                os.makedirs(OUT, exist_ok=True)
                open(path, 'w').write(text)

    orphans = sorted(
        os.path.basename(f) for f in glob.glob(OUT + '/*.md')
        if os.path.basename(f)[:-3] not in names)
    return written, orphans


if __name__ == '__main__':
    check = '--check' in sys.argv
    written, orphans = regenerate_all(check=check)
    total = len(ra.personas())
    if orphans:
        print('orphan agents (fix skills/, do not hand-edit): '
              + ', '.join(orphans), file=sys.stderr)
    if check:
        if written or orphans:
            print('drift: %d of %d agent files stale%s'
                  % (len(written), total,
                     ' — ' + ', '.join(written) if written else ''),
                  file=sys.stderr)
            sys.exit(1)
        print('claude-agents: %d/%d current' % (total, total))
    else:
        print('regenerated %d/%d agents: %s'
              % (len(written), total,
                 ' '.join(written) if written else '(all current)'))
