#!/usr/bin/env python3
# Derive claude-agents/*.md from skills/ — the Claude Code subagent projection,
# sibling to render-agents.py's Codex toml projection.
#
# Why these are SHIMS and not inlined personas. render-agents.py inlines the
# whole persona plus the shared core into each toml, because the Codex CLI has
# no skills mechanism to defer to — the toml has to be self-contained. Claude
# Code does have one, and sync.sh already puts every persona under
# ~/.claude/skills/. Inlining here would put each persona in the profile twice
# and let the copies drift the moment one is edited, which is the exact failure
# render-agents.py's own header records: 174 lines that landed in skills/ and
# never crossed, 63 stale lines left behind, invisible to a plain diff. One
# source of truth, two thin projections.
#
# The shim carries the skill reference two ways on purpose: the frontmatter
# `skills:` field, and a body instruction naming the same skill. If the field
# is honored the body is redundant reinforcement; if it is ever ignored or
# dropped from the schema, the body alone still routes the subagent to the
# right place. A generated file that silently becomes a no-op is worse than a
# slightly redundant one.
#
# What this buys, precisely, turns on skills-vs-subagents precedence, stated
# once in README.md § The claude-agents subagent surface.
#
# Build step (skills/ -> claude-agents/), not a deploy step (repo -> profiles);
# sync.sh does the latter. Deliberately not wired together, same as
# render-agents.py: folding this into sync.sh would make it mutate tracked
# files on every run.
#
# Usage: python3 render-claude-agents.py             # regenerate, idempotent
#        python3 render-claude-agents.py --check     # exit 1 on drift, write nothing
#        python3 render-claude-agents.py --selftest  # break each check, prove it fires
import importlib.util, os, sys, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, 'claude-agents')

# Reuse render-agents.py's parsing rather than reimplementing it. The hyphen in
# the filename blocks a plain import, so load it by path — duplicating
# has_persona_line() or frontmatter_desc() here would create a second surface
# that drifts from the first, which is the thing both scripts exist to prevent.
_spec = importlib.util.spec_from_file_location(
    'render_agents', os.path.join(ROOT, 'render-agents.py'))
ra = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ra)


def render(p, root=ROOT):
    """claude-agents/<p>.md — frontmatter plus a two-sentence body.

    The description is copied verbatim from the skill's frontmatter, never
    rewritten or shortened: it is the trigger surface for both mechanisms, and
    Claude under-triggers skills already. A subagent whose description drifts
    from its skill's is a persona you can reach one way and not the other.
    """
    sk = open('%s/skills/%s/SKILL.md' % (root, p)).read()
    desc = ra.frontmatter_desc(sk, name=p)
    # Prose says "Briar"; identifiers (name, skills, paths) say "briar". The
    # skill file, its description, and every cross-persona reference capitalize
    # the name in prose, so a shim that opens "You are briar." reads as a
    # different, sloppier persona than the one it points at.
    n = p.capitalize()
    # "a Eli" reads as a typo in a file whose whole job is to sound like the
    # persona it points at. Names are ASCII and vowel-initial spelling matches
    # vowel-initial pronunciation across the roster, so first letter decides.
    art = 'an' if n[0] in 'AEIOU' else 'a'
    return (
        '---\n'
        'name: %s\n' % p
        + 'description: >\n  %s\n' % desc
        + 'skills:\n  - %s\n' % p
        + '---\n\n'
        + 'You are %s. The `%s` skill is preloaded into your context at startup '
          'by the `skills:` field above — its full content, not just its '
          'description. That skill is the complete definition of this persona: '
          'its voice, its bounds, what it must not touch, and how it hands off. '
          'Follow it. Nothing about how %s works lives in this file.\n\n'
          'If the skill is somehow absent from your context, say so plainly '
          'rather than improvising a persona from this stub — %s %s running on '
          'guesswork is worse than one that reports it cannot start.\n\n'
          'Generated by render-claude-agents.py from skills/%s/SKILL.md. '
          'Hand-editing is a no-op; the next build overwrites it. Change the '
          'skill instead.\n' % (n, p, n, art, n, p))


def regenerate_all(root=ROOT, check=False):
    """Rewrite every persona's agent file. Returns (written, orphans).

    Iterates personas() — the skills whose SKILL.md opens with a canonical
    persona declaration — not claude-agents/*.md, so a newly added persona gets
    a file the first time this runs. A utility skill (handoff, review-loop,
    devils-advocate) has no declaration and correctly gets none: the absence of
    the line is the signal, exactly as it is for the toml projection.

    An orphan is a claude-agents/*.md with no matching persona in skills/ — a
    skill renamed, removed, or demoted to a utility. Reported by name and left
    untouched rather than deleted, so a rename is a visible warning instead of
    a silent disappearance.

    The output directory is derived from `root`, never from the module-level
    default: a call that renders one tree and writes into another corrupts the
    real tree with content derived from somewhere else, and the obvious caller
    that would hit it is selftest(), which runs against a throwaway copy.

    Renders every persona before writing any file, and reports every malformed
    source rather than aborting on the first — a bare traceback naming one
    offender sends the reader back for another run to find the next.
    """
    out_dir = os.path.join(root, 'claude-agents')
    names = ra.personas(root)

    rendered, errors = {}, []
    for p in names:
        try:
            rendered[p] = render(p, root)
        except ValueError as e:
            errors.append('%s.md: %s' % (p, e))
    if errors:
        raise ValueError('cannot regenerate — fix skills/ source first:\n  '
                         + '\n  '.join(errors))

    written = []
    for p, text in sorted(rendered.items()):
        path = os.path.join(out_dir, p + '.md')
        if not os.path.exists(path) or open(path).read() != text:
            written.append(p)
            if not check:
                os.makedirs(out_dir, exist_ok=True)
                open(path, 'w').write(text)

    orphans = sorted(
        os.path.basename(f) for f in glob.glob(out_dir + '/*.md')
        if os.path.basename(f)[:-3] not in names)
    return written, orphans


def selftest(root=ROOT):
    """Positive control for each check: break one input, confirm --check goes
    red, restore, confirm green. Runs against a throwaway copy so the real tree
    is never mutated — which is only safe because regenerate_all() derives its
    output directory from `root`. A check nobody has watched fail is not
    evidence; this is the sibling's contract, held here too."""
    import shutil, tempfile
    ok = True
    with tempfile.TemporaryDirectory() as tmp:
        r = os.path.join(tmp, 'repo')
        shutil.copytree(root, r, ignore=shutil.ignore_patterns('.git', '__pycache__'))

        base_written, base_orphans = regenerate_all(r, check=True)
        if base_written or base_orphans:
            print('selftest: baseline copy is not clean (%d stale, %d orphan) — '
                  'fix the tree before trusting the controls'
                  % (len(base_written), len(base_orphans)))
            return False
        print('selftest: baseline green over %d personas' % len(ra.personas(r)))

        # drift: a hand-edited agent file no longer matches render() of its source
        p = ra.personas(r)[0]
        path = os.path.join(r, 'claude-agents', p + '.md')
        orig = open(path).read()
        open(path, 'w').write(orig + '\n<!-- drift -->\n')
        red = regenerate_all(r, check=True)[0]
        open(path, 'w').write(orig)
        green = regenerate_all(r, check=True)[0]
        fired, cleared = p in red, not green
        ok &= fired and cleared
        print('selftest: %-13s red=%s green-after-restore=%s'
              % ('drift', 'yes' if fired else 'NO', 'yes' if cleared else 'NO'))

        # orphan: an agent file with no persona behind it
        stray = os.path.join(r, 'claude-agents', 'not-a-persona.md')
        open(stray, 'w').write('stray\n')
        red = regenerate_all(r, check=True)[1]
        os.remove(stray)
        green = regenerate_all(r, check=True)[1]
        fired, cleared = bool(red), not green
        ok &= fired and cleared
        print('selftest: %-13s red=%s green-after-restore=%s'
              % ('orphan', 'yes' if fired else 'NO', 'yes' if cleared else 'NO'))
    return ok


if __name__ == '__main__':
    mode = sys.argv[1] if len(sys.argv) > 1 else ''
    if mode == '--selftest':
        sys.exit(0 if selftest() else 1)
    # An unrecognized argument must never fall through to the write arm: a
    # mistyped `--chek` would regenerate and overwrite tracked files while the
    # caller believed a read-only check ran, and exit 0 either way.
    if mode and mode != '--check':
        print('usage: render-claude-agents.py [--check | --selftest]',
              file=sys.stderr)
        sys.exit(2)
    check = mode == '--check'
    try:
        written, orphans = regenerate_all(check=check)
    except ValueError as e:
        print('error: %s' % e, file=sys.stderr)
        sys.exit(1)
    total = len(ra.personas())
    if orphans:
        print('orphan agents (fix skills/, do not hand-edit): '
              + ', '.join(orphans), file=sys.stderr)
    if check:
        if written or orphans:
            # Only claim stale files when there are stale files. An orphan-only
            # run printing "drift: 0 of 27 agent files stale" contradicts itself
            # and sends the reader hunting for a file that doesn't exist.
            if written:
                print('drift: %d of %d agent files stale — %s'
                      % (len(written), total, ', '.join(written)),
                      file=sys.stderr)
            sys.exit(1)
        print('claude-agents: %d/%d current' % (total, total))
    else:
        print('regenerated %d/%d agents: %s'
              % (len(written), total,
                 ' '.join(written) if written else '(all current)'))
